name: Custom Server

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  
          fetch-depth: 0    

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111'
          extended: true

      - name: Build
        run: hugo --minify
        
      - name: Deploy
        uses: Burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: ./public
          remote_path: /home/jiqiang.fun/public # 需要先手动在远程主机创建该目录，否则会执行失败
          remote_host: ${{ secrets.SERVER_HOST }} # 远程主机 IP
          remote_user: ${{ secrets.SERVER_USER }} # ssh user
          remote_key: ${{ secrets.SERVER_KEY}} # ssh 私钥
